### ISSUE TITLE
[Suggestion] Tag latest commits and create new releases for them

### ISSUE THREAD

**Issue by Aced14** [warhawkreborn/connector_android#2]
Currently, the only GitHub release of the Android version of Warhawk Reborn is v1.1. But commits for latter versions are available (a290d3d05f9e8d68de8301d1fd53d45f2529e0b7 for v1.2.1 and f490c1e139510260c03c2d873036082fc9e34c4b or 3ba204487cc99043e6f67ab7969617f056030a48 for v1.2.4).

IMO there would be value in tagging the latest commits and creating new releases for them on GitHub. Release notes could also be beneficial (especially to mention that the newer versions support hosting and UPnP). Apart from being a good practice, it would also lessen the risk of confusion for users that stumble upon this repo and/or that don't use Google Play.

**Comment by Thalhammer** [comment]
Done
