### ISSUE TITLE
[Bug] Android's back button minimizes the app, doesn't navigate properly

### ISSUE THREAD

**Issue by Aced14** [warhawkreborn/connector_android#3]
I noticed that Android's back button doesn't seem to work properly in the current version of Warhawk Reborn (v1.2.5). Instead of navigating back, it minimizes the app and returns to its start screen.

**Steps to reproduce:**
1. Start the Android version of Warhawk Reborn.
2. Open the left menu.
3. Select "Server list".
4. Select any server to view its detailed information.
5. Press Android's back button.

**Expected outcome:**
The user is brought back to the server list.

**Actual outcome:**
The app gets minimized. Un-minimizing it shows the app's start screen (large red X or green checkmark) instead of the server list.

**Other details:**
* The version of WR I'm using came from Google Play.
* Not sure if this is a longstanding issue or if it started in v1.2.5.
* I don't usually use the Android version of WR.

**Comment by Thalhammer** [comment]
This was indeed an oversight, should be fixed in 1.2.6, which is currently distributed by Google Play. You should get an update in the next couple of days at most.

**Comment by Aced14** [comment]
I'm now getting the expected outcome in 1.2.6 (via Google Play). The back button is also now going backwards in sequence. In other words, I can randomly open different screens via the left menu, then go back to them in the order I browsed to them in each time I press the back button.

@Thalhammer Thanks :)!
